/app/LOTA ai/services/auth/target/debug/build/thiserror-a4d20208200fd4f7/out